### ISSUE TITLE
Report Print Screen Customizations

### ISSUE THREAD

**Issue by Pants44** [josegomez/epicor-editor-helper#22]
Just tried to open the RMAForm print screen customization I just made, and it doesn't seem to pull in the project.

**Comment by josegomez** [comment]
I'll take a look

**Comment by josegomez** [comment]
I was able to open the RMAForm customization just fine. What version of Epicor are you on @Pants44 ? Also can you send me a copy of your customization?

**Comment by Pants44** [comment]
Couldn't tell you what the issue was. Whenever I was trying to load my RMAForm customization which had 0 things done to it, it would not pull in.

After having to redownload the client (for unrelated reasons) and downloading your new helper libraries that were posted a few hours ago, issues are now non existent.

Thanks anyway for taking a look. 

For reference I am on 10.2.500.18
