### ISSUE TITLE
'extension.downloadcustomization not found' error

### ISSUE THREAD

**Issue by bmanners** [josegomez/epicor-editor-helper#25]
I have installed the VS Code extension, added the helper files to the Epicor client (10.2.600) and  set the client folder in the extension settings.  When I run the Download command VS code gives an error.

"Command 'Epicor Customization (DOWNLOAD)' resulted in an error (command 'extension.downloadcustomization' not found)"

Any thoughts on what might be causing this?

Brett

**Comment by josegomez** [comment]
This has been removed from suport we are only maintaining the Visual Studio (Big Boy) version.
https://marketplace.visualstudio.com/items?itemName=josecgomez.EpicorCustomizationEditorVS
