### ISSUE TITLE
No helper files for 10.2.100

### ISSUE THREAD

**Issue by bmanners** [josegomez/epicor-editor-helper#4]
This is an awesome extension for VS code however we are on 10.2.100 and there are no helper files yet. 

I have cloned the repo and created a local version of the helper files for 10.2.100. I can submit a pull request if you are accepting them. Note: I had some referencing issues and had to edit program.cs in the CommonCode which i think is not right so a review would be required.

Cheers
Brett

**Comment by josegomez** [comment]
I will publish a 100 today but if you want to do a PR go for it. Please create a new project for that version (copy the 10.2.200) and change the references.
You shouldn't have to edit commoncode I'll check 
Thanks

**Comment by bmanners** [comment]
I'll submit a PR, I am new at this so hopefully i get it right :-). 

Figured out that i had referenced a newer version of CommandLine library that has a duplicate for the TypeInfo class. Switching to the same version used in the other projects fixed the issue.

Brett

**Comment by josegomez** [comment]
Thanks Brett, I'll re-view and merge in a bit.

**Comment by josegomez** [comment]
Changes merged and published. Thanks!!! All Solved
