### ISSUE TITLE
Here is a crash case.

### ISSUE THREAD

**Issue by mjtbiz** [josegomez/epicor-editor-helper#6]
Jose,

Thanks for doing this, it has tremendous potential.  I just updated VS to 2017 and got the extension installed per your video--nice!.  I grabbed the additional helper files for my version, 10.1.600, and dropped them into the same folder as the Epicor client.  No problem launching the Editor and completing the setup buy identifying the location of the Epicor client and my customization folder. 

Canceling the customization search by closing the search window or clicking the cancel button causes the app to crash.

Hope this helps.

Michael Thompson

Just realized that there are some files available that help describe the crash:
[WERFF02.tmp.appcompat.zip](https://github.com/josegomez/epicor-editor-helper/files/3105457/WERFF02.tmp.appcompat.zip)

**Comment by josegomez** [comment]
This has been fixed (I believe) the latest library. Re-download the helper library and give her a whirl.
