### ISSUE TITLE
No helper files for 10.2.400

### ISSUE THREAD

**Issue by bmanners** [josegomez/epicor-editor-helper#7]
There are no helper files for 10.2.400 yet.

I have started work on this. Will submit a pull request once i have done some testing.

Brett

**Comment by bmanners** [comment]
I have created a new project for 10.2.400 and compiled it, however I am having some trouble testing it. I don't think the issues are related to 10.2.400 as they also happen when i swap back to my 10.2.100 version. When I try to open the toolbox in VS Code I get error below.
![image](https://user-images.githubusercontent.com/11130380/59511811-d561ee80-8ee9-11e9-89e7-eeba1be0bae4.png)

I did successfully open a customization from our 10.2.400 install using the OPEN command so that would indicate the helper files are good. code is here https://github.com/bmanners/epicor-editor-helper/tree/10.2.400_Helper_Files. 

notes:
- I used a reference path for all the Epicor dlls. Add a path to your Epicor client and it should find all the dlls.
- I changed the build output folder to /Bin

Brett

**Comment by josegomez** [comment]
Hi Brett,
The helper files and exe need to all be IN the Epicor Client for it to run correctly. So if you moved it to the Bin folder how are you launching it?
Or do you mean you compiled then copied the files into the Epicor folder then tried to use the extension?

**Comment by bmanners** [comment]
I copied from bin folder into Epicor client folder. Then I tried the
extension. The toolbox command failed but the open command worked.

I also tried reinstalling the extension from the market place using the
complied helper files.

I'll try a full clean install tomorrow - download your published 10.2.100
helper files and see if that works.

Brett

**Comment by bmanners** [comment]
Found the problem....I was using the extension wrong which is causing the error. I was trying to use the toolbox command before i had downloaded a customization. However the Toolbox command needs the customization downloaded first.

Having solved that i was able to test the 10.2.400 helper files and they worked fine.

**Comment by josegomez** [comment]
Thanks Brett, I will download and publish this week!

**Comment by josegomez** [comment]
This has been merged and published. Sorry for the delay, thanks Brett!
