### ISSUE TITLE
Check if Project is saved before launching edit/run

### ISSUE THREAD

**Issue by BVAnderson** [josegomez/epicor-editor-helper#9]
If you make changes in VS, then forget to save the project before clicking the edit/run button , there is no way to get back to what you were doing, and the changes will get blown away when you close the Epicor session that is created. To test it, put some comments in VS, then don't save, then hit the edit/run button. The save as window will pop up behind, but even if you save the customization, the previously save version is already loaded into epicor, so your changes are lost.

I would suggest a check of the save status in VS before the uploading to Epicor so there can be a graceful cancel, (don't open Epicor), save the project before opening, or continute without saving.

**Comment by josegomez** [comment]
This has been fixed in the latest version.
